### ISSUE TITLE
Unable to install ceiba-cli

### ISSUE THREAD

**Issue by junjun-zhang** [nlesc-nano/ceiba-cli#30]
I had trouble installing the ceiba-cli tool using the command from the documentation `pip install git+https://github.com/nlesc-nano/ceiba-cli.git@main`, tried on different computers, gave the same error: `ModuleNotFoundError: No module named 'ceibacli.actions'`

**Comment by felipeZ** [comment]
@junjun-zhang thanks for reporting it I am going to have a look at it.

**Comment by BvB93** [comment]
Just to check: how did you try to access to `actions` module?
Was it via `import ceibacli.actions` or simply a getattr statement (`ceibacli.actions`) with out the explicit import?

Since I don't think the latter will work (without a prior import) as the the `actions` submodule is not loaded by default.

Examples
---------
``` python
>>> import ceibacli.actions  # This should work without raising
```

**Comment by felipeZ** [comment]
The issue may come from a mismatch between the Python interpreter and `pip` itself. In order to avoid this kind of issues, It is better to install the package like:
```
python -m pip install git+https://github.com/nlesc-nano/ceiba-cli.git@main
```
I am also changing the README.

**Comment by felipeZ** [comment]
I have updated the installation instructions and I am closing this issue, feel free to reopen it in case that things are not working as expected.
